### ISSUE TITLE
building

### ISSUE THREAD

**Issue by 200Puls** [PolymerLabs/indie-catalog#1]
Hi @notwaldorf,

i know this is still very early for this component, but we were just about to develop something similar for our internal components when we found this yesterday. So we did a test deployment yesterday and its already proving very useful.

We just had some small problems:

- missing extra dependencies. We had to add the following lines in polymer.json in extra_dependency section
-- bower_components/marked-element/**
-- bower_components/marked/**
-- bower_components/prism/**
-- bower_components/prism-element/**
-- bower_components/paper-styles/**
-  analysis not working
-- It is just outputting a version json for us: "{"schema_version":"1.0.0"}" 
We are working around this by using polymer-cli and generating the analysis using that.
- had to switch to unbundled build
- and this is more of  a feature request. It would be cool to have a branch version for the catalog items. So that we could have one catalog displaying the stable version and one for active development versions.

So again, thanks for this component it has already saved us quite some time. Looking forward to the future development.

**Comment by notwaldorf** [comment]
Thanks so much for trying it out! The extra dependencies are a fair catch -- mind sending a PR with that?

My general comment is that I didn't mean this to be an end-all-and-be-all app (everyone has different opinions on what they _need_ from a catalog), so if there's some features that you want to add, you can totally fork it and add them yourself, rather than wait for someone to add them to this project. That aside, I have a couple of questions:
- why did you _have_ to switch to the unbundled build? That's totally fine (and again, you can do that for your deployed build), but I'm just trying to understand the use case
- is the element that the analyzer is failing available somewhere for @aomarks and i to take a look at?

**Comment by notwaldorf** [comment]
Oshit, actually the docs seem broken in the live site too. Let me investigate.

**Comment by notwaldorf** [comment]
Oh, good. It's fine locally, but borked on the deploy because gulp.

**Comment by notwaldorf** [comment]
Fixed!
